from typing import Dict, List, Set


REGION_CONNECTIONS: Dict[str, Set[str]] = {
        "Menu":                            {"Batcave"},
        "Batcave":                         {"Arkham Asylum", "Shop", "You Can Bank on Batman","An Icy Reception","Two-Face Chase","A Poisonous Appointment","The Face-Off","There She Goes Again","Batboat Battle","Under the City","Zoo's Company","Penguin's Lair","Joker's Home Turf","Little Fun at Big Top","Flight of the Bat","In the Dark Night","To the Top of the Tower"},
        "Shop":                            {"Batcave", "Arkham Asylum"},
        "Arkham Asylum":                   {"Shop","The Riddler Makes a Withdrawl","On the Rocks","Green Fingers","An Enterprising Theft", "Breaking Blocks","Rocking the Docks","Stealing the Show","Harboring a Grudge","A Daring Rescue","Artic World","A Surpise for the Commissioner","Biplane Blast","The Joker's Masterpiece","The Lure of the Night","Dying of Laughter"},
        "You Can Bank on Batman":          {"Status Screen"},
        "An Icy Reception":                {"Status Screen"},
        "Two-Face Chase":                  {"Status Screen"},
        "A Poisonous Appointment":         {"Status Screen"},
        "The Face-Off":                    {"Status Screen"},
        "There She Goes Again":            {"Status Screen"},
        "Batboat Battle":                  {"Status Screen"},
        "Under the City":                  {"Status Screen"},
        "Zoo's Company":                   {"Status Screen"},
        "Penguin's Lair":                  {"Status Screen"},
        "Joker's Home Turf":               {"Status Screen"},
        "Little Fun at Big Top":           {"Status Screen"},
        "Flight of the Bat":               {"Status Screen"},
        "In the Dark Night":               {"Status Screen"},
        "To the Top of the Tower":         {"Status Screen"},
        "The Riddler Makes a Withdrawl":   {"Status Screen"},
        "On the Rocks":                    {"Status Screen"},
        "Green Fingers":                   {"Status Screen"},
        "An Enterprising Theft":           {"Status Screen"},
        "Breaking Blocks":                 {"Status Screen"},
        "Rockin' the Docks":               {"Status Screen"},
        "Stealing the Show":               {"Status Screen"},
        "Harboring a Grudge":              {"Status Screen"},
        "A Daring Rescue":                 {"Status Screen"},
        "Artic World":                     {"Status Screen"},
        "A Surpise for the Commissioner":  {"Status Screen"},
        "Biplane Blast":                   {"Status Screen"},
        "The Joker's Masterpiece":         {"Status Screen"},
        "The Lure of the Night":           {"Status Screen"},
        "Dying of Laughter":               {"Status Screen"},
        "Status Screen":                   {"Batcave", "Arkham Asylum"},
    }
REGIONS: Dict[str, List[str]] = {
"Shop": {"Buy Beep Beep","Buy Silhouettes","Buy Extra Toggle","Buy Disguise","Buy Ice Rink"},
"Status Screen": {"Status Screen - Unlock Detonation Suit", "Status Screen - Unlock Sonic Suit", "Status Screen - Unlock Heat Protection Suit","Status Screen - Unlock Glide Suit","Status Screen - Unlock Technology Suit","Status Screen - Unlock Attraction Suit","Status Screen - Unlock Magnet Suit","Status Screen - Unlock Water Suit"},
"You Can Bank on Batman": { "TRR Hero #1 - Boss Room, Break the bank darwer","Status Screen - You Can Bank On Batman True Status","Status Screen - You Can Bank On Batman Completed"},
"An Icy Reception": {"Status Screen - An Icy Reception Completed","Status Screen - An Icy Reception True Status","TRR Hero #2 - Room 2, Press on switch while other character goes in cage."},
"Two-Face Chase": {"TRR Hero #3 - Room 3, Destroy trash can in the far back left cornor","Status Screen - Two-Face Chase True Status", "Status Screen - Two-Face Chase Completed"},
"A Poisonous Appointment": {"TRR Hero #4 - Room 4, Use the switch, blow up the silver object and use the generator","Status Screen - A Poisonous Appointment Completed","Status Screen - A Poisonous Appointment True Status"},
"The Face-Off": {"Status Screen - The Face-Off True Status","Status Screen - The Face-Off Completed","TRR Hero #5 - Room 2, After Two Face Fight, Push Colored Buttons on left side"},
"There She Goes Again":  {"PCP Hero #1 - Boss Room, Break wall near entrance","Status Screen - There She Goes Again True Status","Status Screen - There She Goes Again Completed"},
"Batboat Battle": {"Status Screen - Batboat Battle Completed", "Status Screen - Batboat Battle True Status","PCP Hero #2 - Boss Room, Submerge and shoot targets"},
"Under the City": {"PCP Hero #3 - Room 1, Use Tech Pannel and run over bouys","Status Screen - Under the City Completed","Status Screen - Under the City True Status"},
"Zoo's Company":  {"Status Screen - Zoo's Company True Status","Status Screen - Zoo's Company Completed","PCP Hero #4 - Room 2, Break Silver gate and go in water"},
"Penguin's Lair": {"Status Screen - Penguin's Lair True Status", "Status Screen - Penguin's Lair Completed","PCP Hero #5 - Boss Room, Break glass near treadmil, graple and jump to rail and run on tredmil then push button"},
"Joker's Home Turf": {"Status Screen - Joker's Home Turf Completed","Status Screen - Joker's Home Turf True Status","TJR Hero #1 - Room 3, Freeze water near entrance then double jump up, then break glass and solve puzzle"},
"Little Fun at Big Top": {"TJR Hero #2 - Room 1, Use Tech Pannel on Crane Game, grab and break all 3 pink prizes", "Status Screen - Little Fun at the Big Top True Status","Status Screen - Little Fun at the Big Top Completed"},
"Flight of the Bat": {"Status Screen - Flight of the Bat Completed","Status Screen - Flight of the Bat True Status","TJR Hero #3 - Room 2, Go through toxic gas and shoot turnstiles"},
"In the Dark Night": {"TJR Hero #4 - Room 3, Build heated ladder then climb, glide and double jump","Status Screen - In the Dark Night Completed","Status Screen - In the Dark Night True Status"},
"To the Top of the Tower": {"Status Screen - To the Top of the Tower True Status","Status Screen - To the Top of the Tower Completed", "TJR Hero #5 - Room 2, Push organ out of hiding, then press button to get guy to play it"},
"The Riddler Makes a Withdrawl": {"TRR Villian #1 - Room 2, Climb magnet wall then double jump and bring down green sign, build it and bring it to crusher in sub room","Status Screen - The Ridler Makes a Withdrawal Completed","Status Screen - The Ridler Makes a Withdrawal True Status"},
"On the Rocks": {"TRR Villian #2 - Room 2, Break silver handle then go inside, break object, build switch, go across and build object","Status Screen - On the Rocks True Status","Status Screen - On the Rocks Completed"},
"Green Fingers": {"Status Screen - Green Fingers Completed","Status Screen - Green Fingers True Status", "TRR Villian #3 - Room 2, Bomb silver door, then go in and use attract machine, use tech pannel to bake cake"},
"An Enterprising Theft": {"TRR Villian #4 - Room 3, Blow up silver door, then build movie player, go in door and solve puzzle","Status Screen - An Enterprising Theft True Status"},
"Breaking Blocks": {"Status Screen - Breaking Blocks True Status","Status Screen - Breaking Blocks Completed","TRR Villian #5 - Room 3, Break silver door then build and push gold block, break glass, break pannel, then blow up silver door"},
"Rockin' the Docks": {"PCP Villian #1 - Room 2, Use female door pannel and solve puzzle", "Status Screen - Rockin' the Docks Completed","Status Screen - Rockin' the Docks True Status"},
"Stealing the Show": {"Status Screen - Stealing the Show True Status","Status Screen - Stealing the Show Completed","PCP Villian #2 - Room 2, Use attract machine then build helicopter then push buttons and blow up silver object"},
"Harboring a Grudge": {"PCP Villian #3 - Boss Room, Torpedo Red Green Yellow wall and drive to left corner","Status Screen - Harboring a Grudge Completed","Status Screen - Harboring a Grudge True Status"}
"A Daring Rescue": {"PCP Villian #4 - Room 5, Build canon to enter sub room, strong push platform, use tech suit to make another platform, jump across"},
"Artic World": {"Status Screen - Arctic World Completed","PCP Villian #5 - Room 1, Use attract machine and play fishing mini game","Status Screen - Arctic World True Status"},
"A Surpise for the Commissioner": {"TJR Villian #1 - Room 2, Glide across from near generator then grapple up and blow up silver object", "Status Screen - A Surprise for the Commissioner True Status","Status Screen - A Surprise for the Commissioner Completed"},
"Biplane Blast": {"TJR Villian #2 - Destroy 5 police copters throughout the level","Status Screen - Biplane Blast True Status","Status Screen - Biplane Blast Completed"},
"The Joker's Masterpiece": {"TJR Villian #3 - Room 1, Bomb silver door, then go in heated room and solve puzzle","Status Screen - The Joker's Masterpiece True Status","Status Screen - The Joker's Masterpiece Completed"},
"The Lure of the Night": {"TJR Villian #4 - Room 2, Use attract machine in playground and grow plants","Status Screen - The Lure of the Night True Status","Status Screen - The Lure of the Night Completed"},
"Dying of Laughter": {"TJR Villian #5 - Room 1, Batarang chandelures then build sweeper and clean church", "Status Screen - Dying of Laughter True Status","Status Screen - Dying of Laughter Completed"},
}

CHAR_SHOP: Dict[str, List[str]] = {
"Shop": {"Buy Bruce Wayne","Buy Alfred","Buy Batgirl","Buy Nightwing","Buy Commissioner Gordon","Buy Mad Hatter","Buy Fishmonger","Buy Scientist","Buy Security Guard","Buy Police Marksman","Buy Police Officer","Buy S.W.A.T.","Buy Sailor","Buy Miltary Police","Buy Yeti","Buy Penguin Minion","Buy Catwoman (Classic)","Buy Man-Bat","Buy Joker (Tropical)","Buy Poison Ivy Goon","Buy Freeze Girl","Buy Zoo Sweeper","Buy Riddler Henchman","Buy Riddler Goon","Buy Penguin Goon","Buy Penguin Henchman","Buy Joker Goon","Buy Clown Goon","Buy Joker Henchman","Buy Police Car","Buy Police Bike","Buy Police Van","Buy Bat-Tank","Buy Two-Face's Armored Truck","Buy Garbage Truck","Buy Catwoman's Motorcycle","Buy Mr.Freeze's Kart","Buy Police Watercraft","Buy Police Boat","Buy Penguin Goon Submarine","Buy Mad Hatter's Steamboat","Buy Robin's Submarine","Buy Mr.Freeze's Iceberg","Buy The Joker Van","Buy Harley Quinn's Hammer Truck","Buy Police Helicopter","Buy Bruce Wayne's Private Jet","Buy Goon Helicopter","Buy Mad Hatter's Glider","Buy Riddler Jet","Buy Harbor Helicopter"},
}