from typing import Dict, List, NamedTuple, Optional

from BaseClasses import MultiWorld, Region, Entrance
from .Locations import RLLocation, location_table, get_locations_by_category


class LegoBatman1RegionData(NamedTuple):
    locations: Optional[List[str]]
    region_exits: Optional[List[str]]

 regions: Dict[str, LegoBatman1RegionData] = {
        "Menu":                            LegoBatman1RegionData(None, ["Batcave"]),
        "Batcave":                         LegoBatman1RegionData(None, ["Arkham Asylum", "Shop", "You Can Bank on Batman","An Icy Reception","Two-Face Chase","A Poisonous Appointment","The Face-Off","There She Goes Again","Batboat Battle","Under the City","Zoo's Company","Penguin's Lair","Joker's Home Turf","Little Fun at Big Top","Flight of the Bat","In the Dark Night","To the Top of the Tower"]),
        "Shop":                            LegoBatman1RegionData([], ["Batcave", "Arkham Asylum"]),
        "Arkham Asylum":                   LegoBatman1RegionData([], ["Batcave","Shop","The Riddler Makes a Withdrawl","On the Rocks","Green Fingers","An Enterprising Theft", "Breaking Blocks","Rocking the Docks","Stealing the Show","Harboring a Grudge","A Daring Rescue","Artic World","A Surpise for the Commissioner","Biplane Blast","The Joker's Masterpiece","The Lure of the Night","Dying of Laughter"]),
        "You Can Bank on Batman":          LegoBatman1RegionData([], ["Status Screen"]),
        "An Icy Reception":                LegoBatman1RegionData([], ["Status Screen"]),
        "Two-Face Chase":                  LegoBatman1RegionData([], ["Status Screen"]),
        "A Poisonous Appointment":         LegoBatman1RegionData([], ["Status Screen"]),
        "The Face-Off":                    LegoBatman1RegionData([], ["Status Screen"]),
        "There She Goes Again":            LegoBatman1RegionData([], ["Status Screen"]),
        "Batboat Battle":                  LegoBatman1RegionData([], ["Status Screen"]),
        "Under the City":                  LegoBatman1RegionData([], ["Status Screen"]),
        "Zoo's Company":                   LegoBatman1RegionData([], ["Status Screen"]),
        "Penguin's Lair":                  LegoBatman1RegionData([], ["Status Screen"]),
        "Joker's Home Turf":               LegoBatman1RegionData([], ["Status Screen"]),
        "Little Fun at Big Top":           LegoBatman1RegionData([], ["Status Screen"]),
        "Flight of the Bat":               LegoBatman1RegionData([], ["Status Screen"]),
        "In the Dark Night":               LegoBatman1RegionData([], ["Status Screen"]),
        "To the Top of the Tower":         LegoBatman1RegionData([], ["Status Screen"]),
        "The Riddler Makes a Withdrawl":   LegoBatman1RegionData([], ["Status Screen"]),
        "On the Rocks":                    LegoBatman1RegionData([], ["Status Screen"]),
        "Green Fingers":                   LegoBatman1RegionData([], ["Status Screen"]),
        "An Enterprising Theft":           LegoBatman1RegionData([], ["Status Screen"]),
        "Breaking Blocks":                 LegoBatman1RegionData([], ["Status Screen"]),
        "Rockin' the Docks":               LegoBatman1RegionData([], ["Status Screen"]),
        "Stealing the Show":               LegoBatman1RegionData([], ["Status Screen"]),
        "Harboring a Grudge":              LegoBatman1RegionData([], ["Status Screen"]),
        "A Daring Rescue":                 LegoBatman1RegionData([], ["Status Screen"]),
        "Artic World":                     LegoBatman1RegionData([], ["Status Screen"]),
        "A Surpise for the Commissioner":  LegoBatman1RegionData([], ["Status Screen"]),
        "Biplane Blast":                   LegoBatman1RegionData([], ["Status Screen"]),
        "The Joker's Masterpiece":         LegoBatman1RegionData([], ["Status Screen"]),
        "The Lure of the Night":           LegoBatman1RegionData([], ["Status Screen"]),
        "Dying of Laughter":               LegoBatman1RegionData([], ["Status Screen"]),
        "Status Screen":                   LegoBatman1RegionData([], ["Batcave", "Arkham Asylum"]),
    }

    regions["You Can Bank on Batman"].locations.append("Status Screen - You Can Bank on Batman Completed"),
    regions["An Icy Reception"].locations.append("Status Screen - An Icy Reception Completed"),    
    regions["Two-Face Chase"].locations.append("Status Screen - Two-Face Chase Completed"),
    regions["A Poisonous Appointment"].locations.append("Status Screen - A Poisonous Appointment Completed"),
    regions["The Face-Off"].locations.append("Status Screen - The Face-Off Completed"),    
    regions["There She Goes Again"].locations.append("Status Screen - There She Goes Again Completed"),
    regions["Batboat Battle"].locations.append("Status Screen - Batboat Battle Completed"),    
    regions["Under the City"].locations.append("Status Screen - Under the City Completed"),
    regions["Zoo's Company"].locations.append("Status Screen - Zoo's Company Completed"),
    regions["Penguin's Lair"].locations.append("Status Screen - Penguin's Lair Completed"),    
    regions["Joker's Home Turf"].locations.append("Status Screen - Joker's Home Turf Completed"),
    regions["Little Fun at Big Top"].locations.append("Status Screen - Little Fun at Big Top Completed"),    
    regions["Flight of the Bat"].locations.append("Status Screen - Flight of the Bat Completed"),
    regions["In the Dark Night"].locations.append("Status Screen - In the Dark Night Completed"),
    regions["To the Top of the Tower"].locations.append("Status Screen - To the Top of the Tower Completed"),
    regions["The Ridler Makes a Withdrawal"].locations.append("Status Screen - The Ridler Makes a Withdrawal Completed"),
    regions["On the Rocks"].locations.append("Status Screen - On the Rocks Completed"),
    regions["Green Fingers"].locations.append("Status Screen - Green Fingers Completed"),
    regions["An Enterprising Theft"].locations.append("Status Screen - An Enterprising Theft Completed"),
    regions["Breaking Blocks"].locations.append("Status Screen - Breaking Blocks Completed"),
    regions["Rockin' the Docks"].locations.append("Status Screen - Rockin' the Docks Completed"),
    regions["Stealing the Show"].locations.append("Status Screen - Stealing the Show Completed"),
    regions["Harboring a Grudge"].locations.append("Status Screen - Harboring a Grudge Completed"),
    regions["A Daring Rescue"].locations.append("Status Screen - A Daring Rescue Completed"),
    regions["Arctic World"].locations.append("Status Screen - Arctic World Completed"),
    regions["A Surprise for the Commissioner"].locations.append("Status Screen - A Surprise for the Commissioner Completed"),
    regions["Biplane Blast"].locations.append("Status Screen - Biplane Blast Completed"),
    regions["The Joker's Masterpiece"].locations.append("Status Screen - The Joker's Masterpiece Completed"),
    regions["The Lure of the Night"].locations.append("Status Screen - The Lure of the Night Completed"),
    regions["Dying of Laughter"].locations.append("Status Screen - Dying of Laughter Completed"),
    regions["Shop"].locations.append("Buy Beep Beep"),
    regions["Shop"].locations.append("Buy Silhouettes"),
    regions["Shop"].locations.append("Buy Extra Toggle"),
    regions["Shop"].locations.append("Buy Disguise"),
    regions["Shop"].locations.append("Buy Ice Rink"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Boss Room, Break the bank darwer"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 2, Press on switch while other character goes in cage"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 3, Destroy trash can in the far back left cornor"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 4, Use the switch, blow up the silver object and use the generator"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 2, After Two Face Fight, Push Colored Buttons on left side"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Boss Room, Break glass wall near entrance"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Boss Room, Submerge and shoot targets"),
    regions["Under The City"].locations.append("PCP Hero #3 - Room 1, Use Tech Pannel and run over bouys"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 2, Break Silver grate and go in water"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Break glass near treadmil, graple and jump to rail and run on tredmil then push button"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 3, Freeze water near entrance then double jump up, then break glass and solve puzzle"),
    regions["Little Fun at the Big Top"].locations.append("TJR Hero #2 - Room 1, Use Tech Pannel on Crane Game, grab and break all 3 pink prizes"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 2, Go through toxic gas and shoot turnstiles"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 3, Build heated ladder then climb, glide and double jump"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 2, Push organ out of hiding, then play it"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 2, Climb magnet wall then double jump and bring down green sign, build it and bring it to crusher in sub room"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 2, Break silver handle then go inside, break object, build switch, go across and build object"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 2, Bomb silver door, then go in and use attract machine, use tech pannel to bake cake"),
    regions["An Enterprising Theft"].locations.append("TRR Villian #4 - Room 3, Blow up silver door, then build movie player, go in door and solve puzzle"),
    regions["Breaking Blocks"].locations.append("TRR Villian #5 - Room 3, Break silver door then build and push gold block, break glass, break pannel, then blow up silver door"),
    regions["Rockin' the Docks"].locations.append("PCP Villian #1 - Room 2, Use female door pannel and solve puzzle"),
    regions["Stealing the Show"].locations.append("PCP Villian #2 - Room 2, Use attract machine then build helicopter then push buttons and blow up silver object"),
    regions["Harboring a Grudge"].locations.append("PCP Villian #3 - Boss Room, Use Robin Torpedo on colored wall and drive to left corner"),
    regions["A Daring Rescue"].locations.append("PCP Villian #4 - Room 5, Build canon to enter sub room, strong push platform, use tech suit to make another platform, jump across"),
    regions["Arctic World"].locations.append("PCP Villian #5 - Room 1, Use attract machine and play fishing mini game"),
    regions["A Surprise for the Commissioner"].locations.append("TJR Villian #1 - Room 2, Glide across from near generator then grapple up and blow up silver object"),
    regions["Biplane Blast"].locations.append("TJR Villian #2 - Destroy 5 police copters throughout the level"),
    regions["The Joker's Masterpiece"].locations.append("TJR Villian #3 - Room 1, Bomb silver door, then go in heated room and solve puzzle"),
    regions["The Lure of the Night"].locations.append("TJR Villian #4 - Room 2, Use attract machine in playground and grow plants"),
    regions["Dying of Laughter"].locations.append("TJR Villian #5 - Room 1, Batarang chandelures then build sweeper and clean church"),
    #Hostages
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 1, Break window near spawn and defeat enemeies"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 1, Inside Mind Control Door left of spawn, defeat enemies"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 2, Break glass wall and defeat enemies"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Use Attract Machine and Double Jump on Leaves, defeat enemies"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Fall down rails and defeat enemies, after first Catwoman fight"),
    regions["Under The City"].locations.append("PCP Hero #3 - Room 1, Far Right of room, defeat enemy"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 2, Near batman suit in glass wall, defeat enemies"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, On the far right side of room, defeat enemies"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 3, Use generator far right of room and use elevator and defeat enemies"),
    regions["Little Fun at the Big Top"].locations.append("TJR Hero #2 - Room 2, Defeat enemies top right of tea cups"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 3, Defeat enemies south of spawn"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Bottom left of spawn, defeat enemies"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 2, Break Glass and defeat enemies"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 2, Break silver handle then go inside and defeat enemies"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 2, Bomb silver door, then go in and defeat enemy"),
    regions["An Enterprising Theft"].locations.append("TRR Villian #4 - Room 1, Break glass door to meeting room then defeat enemy"),
    regions["Breaking Blocks"].locations.append("TRR Villian #5 - Room 3, Break silver door then defeat enemy in sub room"),
    regions["Rockin' the Docks"].locations.append("PCP Villian #1 - Room 1, Break glass window and defeat enemy"),
    regions["Stealing the Show"].locations.append("PCP Villian #2 - Room 1, Break strength box, then build magnet wall, break window and defeat enemy"),
    regions["A Daring Rescue"].locations.append("PCP Villian #4 - Room 2, Use generator and go in sub room, then defeat enemies"),
    regions["Arctic World"].locations.append("PCP Villian #5 - Room 1, Swim across toxic water and defeat enemies"),
    regions["A Surprise for the Commissioner"].locations.append("TJR Villian #1 - Room 1, Blow up silver gate and defeat enemies"),
    regions["The Joker's Masterpiece"].locations.append("TJR Villian #3 - Room 1, Bomb silver door, then go in heated room, and defeat enemies"),
    regions["The Lure of the Night"].locations.append("TJR Villian #4 - Room 1, Build rails, then double jump up and defeat enemies"),
    regions["Dying of Laughter"].locations.append("TJR Villian #5 - Room 2, Glide from cage and defeat enemy"),
    #ShopChars
    regions["Shop"].locations.append("Buy Bruce Wayne"),
    regions["Shop"].locations.append("Buy Alfred"),
    regions["Shop"].locations.append("Buy Batgirl"),
    regions["Shop"].locations.append("Buy Nightwing"),
    regions["Shop"].locations.append("Buy Commissioner Gordon"),
    regions["Shop"].locations.append("Buy Mad Hatter"),
    regions["Shop"].locations.append("Buy Fishmonger"),
    regions["Shop"].locations.append("Buy Scientist"),
    regions["Shop"].locations.append("Buy Security Guard"),
    regions["Shop"].locations.append("Buy Commissioner Gordon"),
    regions["Shop"].locations.append("Buy Police Marksman"),
    regions["Shop"].locations.append("Buy Police Officer"),
    regions["Shop"].locations.append("Buy S.W.A.T."),
    regions["Shop"].locations.append("Buy Sailor"),
    regions["Shop"].locations.append("Buy Miltary Police"),
    regions["Shop"].locations.append("Buy Yeti"),
    regions["Shop"].locations.append("Buy Penguin Minion"),
    regions["Shop"].locations.append("Buy Catwoman (Classic)"),
    regions["Shop"].locations.append("Buy Man-Bat"),
    regions["Shop"].locations.append("Buy Joker (Tropical)"),
    regions["Shop"].locations.append("Buy Poison Ivy Goon"),
    regions["Shop"].locations.append("Buy Freeze Girl"),
    regions["Shop"].locations.append("Buy Zoo Sweeper"),
    regions["Shop"].locations.append("Buy Riddler Goon"),
    regions["Shop"].locations.append("Buy Riddler Henchman"),
    regions["Shop"].locations.append("Buy Penguin Goon"),
    regions["Shop"].locations.append("Buy Penguin Henchman"),
    regions["Shop"].locations.append("Buy Joker Goon"),
    regions["Shop"].locations.append("Buy Clown Goon"),
    regions["Shop"].locations.append("Buy Joker Henchman"),
    regions["Shop"].locations.append("Buy Police Car"),
    regions["Shop"].locations.append("Buy Police Bike"),
    regions["Shop"].locations.append("Buy Police Van"),
    regions["Shop"].locations.append("Buy Bat-Tank"),
    regions["Shop"].locations.append("Buy Two-Face's Armored Truck"),
    regions["Shop"].locations.append("Buy Garbage Truck"),
    regions["Shop"].locations.append("Buy Catwoman's Motorcycle"),
    regions["Shop"].locations.append("Buy Mr.Freeze's Kart"),
    regions["Shop"].locations.append("Buy Police Watercraft"),
    regions["Shop"].locations.append("Buy Police Boat"),
    regions["Shop"].locations.append("Buy Penguin Goon Submarine"),
    regions["Shop"].locations.append("Buy Mad Hatter's Steamboat"),
    regions["Shop"].locations.append("Buy Robin's Submarine"),
    regions["Shop"].locations.append("Buy Mr.Freeze's Iceberg"),
    regions["Shop"].locations.append("Buy The Joker Van"),
    regions["Shop"].locations.append("Buy Harley Quinn's Hammer Truck"),
    regions["Shop"].locations.append("Buy Police Helicopter"),
    regions["Shop"].locations.append("Buy Bruce Wayne's Private Jet"),
    regions["Shop"].locations.append("Buy Goon Helicopter"),
    regions["Shop"].locations.append("Buy Mad Hatter's Glider"),
    regions["Shop"].locations.append("Buy Riddler Jet"),
    regions["Shop"].locations.append("Buy Harbor Helicopter"),
    #minikits
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 1, Top Of ladder near switch and grapple"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 1, Garage Door from switch near grapple and ladder"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Break 5 Telephone Booths through out level"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 1, Glass Window near spawn"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 1, Mind Control pannel near toxins"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 1, In the sewer lid with garbage can on it"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 1, Grapple under garbage can to silver window"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 2, Pull window to stairs and walk in"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 2, 2 cars in the garage near toxins"),
    regions["You Can Bank On Batman"].locations.append("TRR Hero #1 - Room 2, Attract Suit machine behind glass wall"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 1, Build and Climb rails on the right of spawn"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 1, Destroy Wood Barrier right of spawn after climbing rails"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 1, Strength behind truck left of spawn"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 1, Climb Rails inside Mind Control Door left of spawn"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 1, Silver object above rails behind gate north of spawn"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 1, Drive truck to platform by spawn and blow up silver objects"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 2, Use female door and blow up silver objects"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 3, Press switch near toxic gas and blow up silver object"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 3, Glide across, blow up vent near fan and ride fan"),
    regions["An Icy Reception"].locations.append("TRR Hero #2 - Room 3, Glide across, mind control guy to pull switch"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 1, Destroy 3 dumpsters"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 1, Destroy the manhole cover south of spawn"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 2, Destroy trash dumpster, southwest of entrance"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 2, Destroy 3 blue cars"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 2, Down the ramp, press the pannel with Joker's Van"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 2, Down the ramp, press the pannel with Harley's Truck"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 2, Destroy the north set of supports"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 2, Destroy the south set of supports"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Room 3, Destroy telephon booth in the far back left"),
    regions["Two-Face Chase"].locations.append("TRR Hero #3 - Destroy 3 food carts through out level"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 1, Build and destroy all carrots"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 1, Jump on the tree off of the tractor, jump to the right tree"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 2, Go through the heat gas and use the tech pad"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 2, push the glass box and jump on flowers"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 2, Build potted plant and double jump to rail"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Build 3 carrots through out level"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 3, Sink down near entrance"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 3, Magnet walk up from rail and blow up silver object"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 4, Jump on the back pipe and walk right"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 5, Jump from rail"),     
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, After gap Jump on all 5 poles"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Far Right side of room grapple"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Use Tech Pad and go through revolving door"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Build Neon Giant Dollar Sign"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Use Attract Machine and Double Jump on Leaves and Double jump"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 2, After Two Face Fight, jump down bridge into toxin"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 2, After Two Face Fight, right side grow plant"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 4, Use the switch, blow up the silver object and use the generator"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Boss Room, Right side opening"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Boss Room, Destroy 5 large containers of money"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Inside Female Pannel Door, South Magnet Wall"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Break South Purple Box, build car, drive car in garage by robin suit"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Blow Up silver barrels then build telephone pole, pull switch and sink"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Find 3 Carrots"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Build Blue Machine near dock and sink"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Build and Destroy flowers near bridge"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Remove Trash Can near bridge and grapple"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Remove Trash Can near fan and go under"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Use tech pad to push buttons, blow up silver, fly to glass pannel up left"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Use tech pad to push buttons, blow up silver, fly to glass pannel right and sink"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 1, Power Light House and use ramp"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 1, Blow up wall near silver gate, blow bomb into silver box"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 1, Submerge and hit 2 buttons, then sink ship with torpedos"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 1, Pull pipe near door"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 2, Submerge under ice"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 2, Destroy Silver Box on Toxic Water"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 2, Blow Up Silver around pipe"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Shoot 3 buoys with torpedo"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Boss Room, Submerge under ice again"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Boss Room, Destroy Silver Boxes on Toxic Water again"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 1, Glide from robin suit and use mind control door, open cage"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 1, Double Jump from rail near middle of room"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 2, Pull Blue Garbage can and break glass"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 2, Double jump from robin suit to rail and walk left"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 2, Use Attract Machine near rails from far right of room, use boat and hit buoys"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Walk through toxins and pull switch"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Near silver gate, build Toilet and push it, then double jump up"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Use extention platform to blow up silver object and jump"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Sink in sewer water after raising it"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Build Machine and use generator"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 1, Use Female Pannel, blow up silver objects and run over bouys"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 1, Open Strength Gate and cross toxic and double jump up"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 1, Use Attract Machine, pieces found across the room"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 1, Double Jump from vending machine and blow up silver objects"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 2, Build totem then grow plant"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 2, Break silver rocks in lion enclosure"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 2, Top right cornor of elephant enclosure"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 3, Jump on big lily pad behind boat"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 3, Freeze water near waterfall and jump up"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 3, Use strength thing near batman suit"),   
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Break glass cover near spawn and sink down"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Freeze water near silver gate and blow it up"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Double Jump on rails to roof of cabin"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Grow 3 carrots all in room 1"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Right side of room break trees, grapple and glide"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Glide to ice berg in back of room"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Double jump up in right of room"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Explode silver object left of room with penguin then walk in toxins"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Break glass near treadmil and build heated object"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Batarang machines connected during fight after blowing up tredmills"),   
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 1, Blow up silver objects and build fan"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 1, Suck up all toxins in room and then deposit them in machine far right of room"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 1, Go in to mind control pannel room and solve puzzle"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 1, Use generator and double jump up to rail"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 2, Use Tech Pannel to blow up exhaust pipes then build."),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 2, Pull switch in toxins"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 2, Use strength and double jump to rails"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 2, Swim in toxin waters near the end of the room"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 3, Use generator far right of room and use elevator and push turnstile"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Boss Room, Climb up magnet wall and push ramp down"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 1, Push bus behind spawn then pull trash can, double jump up and build tight rope"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 1, Break glass infront of carnival game, break carnival game"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 1, Blow Up silver object above carnival game and sink"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 1, Use Tech Pannel on duck game, then destroy all ducks"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 2, Break glass & silver object, build grapple and grapple up"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 2, Use generator near tea cups, after it spins go in bottom left cup"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 2, Ride down spiral slide"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 3, Use tech pad to bring colored boats in the correct colored homes"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 3, Pull door and ride bumper cars"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 3, Go across toxins near boss entrance, grapple and build tightrope"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 1, Destroy all 6 missle launchers"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 1, Fly near silver pipe on the right"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 1, Fly up on railway"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 1, Blow up silver object near hotel sign"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 2, Shoot grey pipe"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 2, Destroy 3 silver valves"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 2, Torpedo gray barrel and tow blue barrel to button"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Boss Room, Go through toxic gas and shoot stuff"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Boss Room, Shoot all 3 near toxic gas"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Boss Room, Fly south and grab item"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 1, Use Strength on door and break glass"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 1, Use generator and double jump on ladder, then break glass"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 1, Jump on rails and go to grapple, grapple up and go to back left corner"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 1, Destroy 3 cakes"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 2, Grow 3 plants then sink in fish tank"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 2, Use attract machine to build helicopter, then use tech pannel to fly helicopter into buttons in center of room"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 3, Pull truck away from garage and blow up silver obeject"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 3, Go across toxins then blow up silver objects, build and walk on magnet wall"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 3, Blow up 3rd silver sewer lid"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Boss Room, Break glass and use generator"),   
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Blow up 3 silver gargoyles"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Left of room, break potted plants and build ladder then press buttons"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Left side of room, build magnet wall, break glass"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Use attract machine right side of room"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Pull switch then jump to platform, near robin suit"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Use generator on right side"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 2, Climb up magnet wall then walk along edge"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 2, Climb up magnet wall then walk a little past switch"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Boss Room, Cause train crash from Batman Torpedo in back then blow up silver pipe"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Boss Room, Blow up silver object right side"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 1, Pull garbage cans with strong character"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 1, Pull white truck in parking lot then double jump up"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 1, Drive Blue car to machine in bottom right of parking lot"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 2, Break silver window near glass"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 2, Batarang window then grapple up to it"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 2, Break glass window with tv after silver gate"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 3, Double jump on rails near entrance"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 3, Break barrels left side of bank"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 3, Break glass window near ladder"),
    regions["The Ridler Makes a Withdrawal"].locations.append("TRR Villian #1 - Room 3, Blow up silver object near police car"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 1, Drive Ice Cream truck into garage"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 1, Break 3 snowmen (One is in glass door sub room)"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 1, Pull window near fan"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 2, Break silver handle then go inside near ladder"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 2, Walk up magnet wall then go down"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 3, Go up elevator then go left, jump down rails"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 3, Use attract machine"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 3, Blow up silver handle then blow up silver object inside with guy"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 4, Walk up magnet wall then glide"),
    regions["On the Rocks"].locations.append("TRR Villian #2 - Room 4, Mind control guy to the left side"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 1, Use tech pannel at spawn then drive car through flags"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 1, Blow up 2 silver gates, then grapple twice, then double jump"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 1, Left side jump on rails"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 3, Blow up silver door then solve pushing puzzle"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 4, Sink in hole in fountain then break glass and pull switch"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 5, Break glass then build magnet wall"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 6, Blow up silver door, break machine, build magnet wall, push it, walk on wall"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 6, Grapple onto heated pipe, then go in hole near heated pipe"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 6, Break glass door then sink, walk forward then swim up"),
    regions["Green Fingers"].locations.append("TRR Villian #3 - Room 7, Blow up silver object left side of room"),
    
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 1, Build and destroy all carrots"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 1, Jump on the tree off of the tractor, jump to the right tree"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 2, Go through the heat gas and use the tech pad"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 2, push the glass box and jump on flowers"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 2, Build potted plant and double jump to rail"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Build 3 carrots through out level"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 3, Sink down near entrance"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 3, Magnet walk up from rail and blow up silver object"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 4, Jump on the back pipe and walk right"),
    regions["A Poisonous Appointment"].locations.append("TRR Hero #4 - Room 5, Jump from rail"),     
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, After gap Jump on all 5 poles"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Far Right side of room grapple"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Use Tech Pad and go through revolving door"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Build Neon Giant Dollar Sign"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 1, Use Attract Machine and Double Jump on Leaves and Double jump"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 2, After Two Face Fight, jump down bridge into toxin"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 2, After Two Face Fight, right side grow plant"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Room 4, Use the switch, blow up the silver object and use the generator"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Boss Room, Right side opening"),
    regions["The Face-Off"].locations.append("TRR Hero #5 - Boss Room, Destroy 5 large containers of money"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Inside Female Pannel Door, South Magnet Wall"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Break South Purple Box, build car, drive car in garage by robin suit"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Blow Up silver barrels then build telephone pole, pull switch and sink"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Find 3 Carrots"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 1, Build Blue Machine near dock and sink"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Build and Destroy flowers near bridge"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Remove Trash Can near bridge and grapple"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Remove Trash Can near fan and go under"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Use tech pad to push buttons, blow up silver, fly to glass pannel up left"),
    regions["There She Goes Again"].locations.append("PCP Hero #1 - Room 2, Use tech pad to push buttons, blow up silver, fly to glass pannel right and sink"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 1, Power Light House and use ramp"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 1, Blow up wall near silver gate, blow bomb into silver box"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 1, Submerge and hit 2 buttons, then sink ship with torpedos"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 1, Pull pipe near door"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 2, Submerge under ice"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 2, Destroy Silver Box on Toxic Water"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Room 2, Blow Up Silver around pipe"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Shoot 3 buoys with torpedo"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Boss Room, Submerge under ice again"),
    regions["Batboat Battle"].locations.append("PCP Hero #2 - Boss Room, Destroy Silver Boxes on Toxic Water again"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 1, Glide from robin suit and use mind control door, open cage"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 1, Double Jump from rail near middle of room"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 2, Pull Blue Garbage can and break glass"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 2, Double jump from robin suit to rail and walk left"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 2, Use Attract Machine near rails from far right of room, use boat and hit buoys"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Walk through toxins and pull switch"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Near silver gate, build Toilet and push it, then double jump up"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Use extention platform to blow up silver object and jump"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Sink in sewer water after raising it"),
    regions["Under the City"].locations.append("PCP Hero #3 - Room 3, Build Machine and use generator"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 1, Use Female Pannel, blow up silver objects and run over bouys"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 1, Open Strength Gate and cross toxic and double jump up"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 1, Use Attract Machine, pieces found across the room"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 1, Double Jump from vending machine and blow up silver objects"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 2, Build totem then grow plant"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 2, Break silver rocks in lion enclosure"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 2, Top right cornor of elephant enclosure"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 3, Jump on big lily pad behind boat"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 3, Freeze water near waterfall and jump up"),
    regions["Zoo's Company"].locations.append("PCP Hero #4 - Room 3, Use strength thing near batman suit"),   
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Break glass cover near spawn and sink down"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Freeze water near silver gate and blow it up"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Double Jump on rails to roof of cabin"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Grow 3 carrots all in room 1"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Room 1, Right side of room break trees, grapple and glide"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Glide to ice berg in back of room"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Double jump up in right of room"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Explode silver object left of room with penguin then walk in toxins"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Break glass near treadmil and build heated object"),
    regions["Penguin's Lair"].locations.append("PCP Hero #5 - Boss Room, Batarang machines connected during fight after blowing up tredmills"),   
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 1, Blow up silver objects and build fan"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 1, Suck up all toxins in room and then deposit them in machine far right of room"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 1, Go in to mind control pannel room and solve puzzle"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 1, Use generator and double jump up to rail"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 2, Use Tech Pannel to blow up exhaust pipes then build."),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 2, Pull switch in toxins"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 2, Use strength and double jump to rails"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 2, Swim in toxin waters near the end of the room"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Room 3, Use generator far right of room and use elevator and push turnstile"),
    regions["Joker's Home Turf"].locations.append("TJR Hero #1 - Boss Room, Climb up magnet wall and push ramp down"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 1, Push bus behind spawn then pull trash can, double jump up and build tight rope"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 1, Break glass infront of carnival game, break carnival game"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 1, Blow Up silver object above carnival game and sink"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 1, Use Tech Pannel on duck game, then destroy all ducks"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 2, Break glass & silver object, build grapple and grapple up"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 2, Use generator near tea cups, after it spins go in bottom left cup"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 2, Ride down spiral slide"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 3, Use tech pad to bring colored boats in the correct colored homes"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 3, Pull door and ride bumper cars"),
    regions["Little Fun at Big Top"].locations.append("TJR Hero #2 - Room 3, Go across toxins near boss entrance, grapple and build tightrope"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 1, Destroy all 6 missle launchers"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 1, Fly near silver pipe on the right"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 1, Fly up on railway"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 1, Blow up silver object near hotel sign"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 2, Shoot grey pipe"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 2, Destroy 3 silver valves"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Room 2, Torpedo gray barrel and tow blue barrel to button"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Boss Room, Go through toxic gas and shoot stuff"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Boss Room, Shoot all 3 near toxic gas"),
    regions["Flight of the Bat"].locations.append("TJR Hero #3 - Boss Room, Fly south and grab item"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 1, Use Strength on door and break glass"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 1, Use generator and double jump on ladder, then break glass"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 1, Jump on rails and go to grapple, grapple up and go to back left corner"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 1, Destroy 3 cakes"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 2, Grow 3 plants then sink in fish tank"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 2, Use attract machine to build helicopter, then use tech pannel to fly helicopter into buttons in center of room"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 3, Pull truck away from garage and blow up silver obeject"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 3, Go across toxins then blow up silver objects, build and walk on magnet wall"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Room 3, Blow up 3rd silver sewer lid"),
    regions["In the Dark Night"].locations.append("TJR Hero #4 - Boss Room, Break glass and use generator"),   
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Blow up 3 silver gargoyles"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Left of room, break potted plants and build ladder then press buttons"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Left side of room, build magnet wall, break glass"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Use attract machine right side of room"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Pull switch then jump to platform, near robin suit"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 1, Use generator on right side"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 2, Climb up magnet wall then walk along edge"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Room 2, Climb up magnet wall then walk a little past switch"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Boss Room, Cause train crash from Batman Torpedo in back then blow up silver pipe"),
    regions["To the Top of the Tower"].locations.append("TJR Hero #5 - Boss Room, Blow up silver object right side"),